#VERSION 1.0
#Author: Creat by Gaetan STEIB, 279981 Supinfo Strabourg

#Origin image
FROM nginx:latest

#Maintainer information
MAINTAINER gaetan steib gaetan.steib@supinfo.com

# Clone our private GitHub Repository
RUN git clone -b docker https://github.com/diranetafen/static-website-example.git /website/
RUN cp -R /website/* /var/www/html/

#Prerequisite
RUN sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-enabled/default

EXPOSE 8080
ENTRYPOINT ["/usr/sbin/nginx","-g","daemon off;"]
