#VERSION 1.0
#Author: Creat by Gaetan STEIB, 279981 Supinfo Strabourg

#Origin image
FROM haproxy:2.3

#Maintainer information
MAINTAINER gaetan steib gaetan.steib@supinfo.com

#Copy info
COPY files/haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
